version: '3'

services:
  ua-rotator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ua-rotator
    ports:
      - "5002:5000"
    volumes:
      - ua-rotator-data:/data
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DATA_DIR=/data
      - DEBUG=false
    restart: unless-stopped
    networks:
      - scraper-network

volumes:
  ua-rotator-data:
    driver: local

networks:
  scraper-network:
    external: true
