global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram-notifications'
  routes:
  - match:
      alertname: SystemStarted
    receiver: 'telegram-notifications'
    group_wait: 0s
  - match_re:
      alertname: ^((?!SystemStarted).)*$
    receiver: 'null-receiver'
    continue: false

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '${TELEGRAM_BOT_TOKEN}'
    api_url: 'https://api.telegram.org'
    chat_id: ${TELEGRAM_CHAT_ID}
    parse_mode: 'HTML'
    
- name: 'null-receiver'
  # Пустой получатель для отбрасывания ненужных алертов

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 