FROM grafana/grafana:10.0.0

COPY grafana-dashboards /etc/grafana/provisioning/dashboards/
COPY grafana-datasources /etc/grafana/provisioning/datasources/

RUN mkdir -p /var/lib/grafana/dashboards
COPY grafana-dashboards/*.json /var/lib/grafana/dashboards/

# Нет необходимости явно менять владельца, т.к. базовый образ 
# уже настроен на правильные разрешения
# grafana/grafana уже запускается от имени пользователя grafana 