global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'scrapyd1'
    static_configs:
      - targets: ['scrapyd1:6800']

  - job_name: 'scrapyd2'
    static_configs:
      - targets: ['scrapyd2:6800']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 