FROM grafana/grafana:9.5.2

USER root

# Copy dashboard provisioning
COPY ./grafana/dashboards /etc/grafana/provisioning/dashboards
COPY ./grafana/datasources /etc/grafana/provisioning/datasources

# Use numeric ID directly to avoid user/group name issues
RUN chown -R 472:472 /etc/grafana/provisioning/

USER grafana

RUN mkdir -p /var/lib/grafana/dashboards
COPY grafana-dashboards/*.json /var/lib/grafana/dashboards/

# Note: We're using UID/GID 472 which is the standard for Grafana
# The grafana/grafana image is already configured to run as this user 