global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'null-receiver'  # Default receiver
  routes:
  - match:
      alertname: SystemStarted
    receiver: 'telegram-notifications'
    group_wait: 0s

receivers:
- name: 'telegram-notifications'
  webhook_configs:
  - url: 'http://telegram-alerts:8080'
    send_resolved: true
    
- name: 'null-receiver'
  # Empty receiver to discard unwanted alerts

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 