groups:
- name: scraper_alerts
  rules:
  - alert: SystemStatus
    expr: up{job="prometheus"} == 1
    labels:
      severity: none
      suppress_default: "true"
    annotations:
      summary: "Система мониторинга активна"
      description: "Все компоненты системы мониторинга функционируют нормально."

  - alert: ScrapydInstanceDown
    expr: up{job=~"scrapyd.*"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Недоступен инстанс Scrapyd"
      description: "Scrapyd инстанс {{ $labels.instance }} недоступен более 1 минуты."

  - alert: ApiGatewayDown
    expr: up{job="api_gateway"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "API Gateway недоступен"
      description: "API Gateway инстанс {{ $labels.instance }} недоступен более 1 минуты."

  - alert: HighMemoryUsage
    expr: container_memory_usage_bytes{name=~"scrapyd.*|selenium.*"} / container_spec_memory_limit_bytes{name=~"scrapyd.*|selenium.*"} > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Высокое использование памяти"
      description: "Контейнер {{ $labels.name }} использует >85% доступной памяти более 5 минут."

  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total{name=~"scrapyd.*|selenium.*"}[1m])) by (name) / sum(container_spec_cpu_shares{name=~"scrapyd.*|selenium.*"}) by (name) / 100 > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Высокая загрузка CPU"
      description: "Контейнер {{ $labels.name }} использует >85% CPU более 5 минут." 